apply plugin: 'com.android.application'

android {
    namespace "com.metrosoft.smart.emr.emrdroid.gt101"
    compileSdkVersion 36
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.metrosoft.smart.emr.emrdroid.gt101"
        minSdkVersion 14
        targetSdkVersion 36
        multiDexEnabled true // 2026.04.14 WOOIL - 추가
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    useLibrary 'org.apache.http.legacy'
}

dependencies {
    implementation 'com.android.support:support-v4:+'
    implementation 'com.android.support:appcompat-v7:+'
    implementation 'com.android.support.constraint:constraint-layout:2.0.4'
    // 2025.12.08 WOOIL - 아래 두 개 추가
    // 바코드 스캐너(예시 버전, 실제로는 프로젝트에 맞는 버전 선택)
    implementation 'com.journeyapps:zxing-android-embedded:3.6.0@aar'
    implementation 'com.google.zxing:core:3.3.0'
    // 2026.04.13 WOOIL - 추가
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
    // 2026.04.14 WOOIL - 추가
    implementation 'com.android.support:multidex:1.0.3'
}
